### ISSUE TITLE
Where are your eyes pointing?

### ISSUE THREAD

**Issue by anko** [wookiehangover/wookiehangover.com#2]
Hi,

I love that you are the cursor, but your un-augmented presence is hard to click with: I can't tell where you're looking until your eyes laser it.

Suggestions: ![little arrow thing](https://user-images.githubusercontent.com/5231746/29412774-fa89a5ea-8351-11e7-89a0-5cf7c78e3dae.png) ![star](https://user-images.githubusercontent.com/5231746/29412773-fa5161da-8351-11e7-9010-df3ac676ff15.png) ![laser pointer dot](https://user-images.githubusercontent.com/5231746/29412965-b38e6ce2-8352-11e7-836d-07f087340eef.png)

**Comment by wookiehangover** [comment]
That's a great suggestion!

**Comment by wookiehangover** [comment]
I tried out option number 3, will be deployed shortly.

**Comment by anko** [comment]
:+1: nice!
